config/routes.rb
Spree::Core::Engine.routes.draw do
  get '/sitemap' => 'sitemap#index'

  namespace :admin do
    resource :sitemap
  end
end

app/models/spree/sitemap_configuration.rb
module Spree
  class SitemapConfiguration < Preferences::Configuration
    preference :include_product_groups,     :boolean, :default => true
    preference :include_product_taxonomies, :boolean, :default => true
    preference :static_pages, :string, :default => ""
  end
end

app/controllers/spree/admin/sitemaps_controller.rb
module Spree
  class Admin::SitemapsController < Admin::BaseController
    def update
      Spree::Sitemap::Config.preferences.keys.each do |key|
        Spree::Sitemap::Config.set(key, params[key]) if params[key].present?
      end

      respond_to do |format|
        format.html {
          redirect_to admin_sitemap_path
        }
      end
    end
  end
end

app/controllers/spree/sitemap_controller.rb
module Spree
  class SitemapController < BaseController
    def index
      # render :text => "Test"
      respond_to do |format|
        format.xml {  }
      end
    end
  end
end

app/views/spree/admin/sitemaps/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1><%= t("sitemap_settings") %></h1>

<%= form_tag(admin_sitemap_path, :method => :put) do %>
  <fieldset id="preferences" data-hook>
    <p>
      <label>
        <%= preference_field_tag(:include_product_groups, Spree::Sitemap::Config[:include_product_groups], :type => :boolean) %>
        <%= t("sitemap_include_product_groups") %>
      </label>
    </p>
    <p>
      <label>
        <%= preference_field_tag(:include_product_taxonomies, Spree::Sitemap::Config[:include_product_taxonomies], :type => :boolean) %>
        <%= t("sitemap_include_product_taxonomies") %>
      </label>
    </p>

    <label><%= t("sitemap_static_pages") %></label>
    <%= preference_field_tag(:static_pages, Spree::Sitemap::Config[:static_pages], :type => :string) %>
  </fieldset>
  <p class="form-buttons">
    <%= button t('update') %>
    <%= t("or") %> <%= link_to t("cancel"), admin_sitemap_url %>
  </p>
<% end %>

app/views/spree/admin/sitemaps/show.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<h1><%= t("sitemap_settings") %></h1>

<table>
  <tr>
    <th scope="row"><%= t("sitemap_include_product_groups") %>:</th>
    <td><%= Spree::Sitemap::Config[:include_product_groups] %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("sitemap_include_product_taxonomies") %>:</th>
    <td><%= Spree::Sitemap::Config[:include_product_taxonomies] %></td>
  </tr>
  <tr>
    <th scope="row"><%= t("sitemap_static_pages") %>:</th>
    <td><%= Spree::Sitemap::Config[:static_pages] %></td>
  </tr>
</table>

<p><%= link_to_with_icon 'edit', t("edit"), edit_admin_sitemap_path, :id => 'admin_sitemap_link' %></p>